name: build
on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: plugin/build/libs/
